apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: k8s-auto-scaler
rules:
- apiGroups: ["apps", "batch", ""]
  resources: ["jobs", "pods"]
  verbs: ["create", "list"]