apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-auto-scaler
subjects:
  - kind: ServiceAccount
    name: k8s-auto-scaler
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: k8s-auto-scaler
  apiGroup: rbac.authorization.k8s.io